### PR TITLE
Add MPC320 support and framework for managing Thorlabs APT devices

### PR DESCRIPTION
**Pull request by auspicacious**
See https://github.com/moonshot-nagayama-pj/PnPQ/issues/51 for additional background. I think that we should consider this as closes https://github.com/moonshot-nagayama-pj/PnPQ/issues/51 , although the requirements have changed during development. (I will note that in the issue).

I've made a couple more changes to the logic since the demo on 10-03. In particular, I noticed that I was not acquiring the `tx_connection_lock` in the appropriate place in the ordered_sender thread.

If you are connected to the hardware, you can run tests by running `pytest hardware_tests`. You will need to adjust the serial number in `hardware_tests/test_polarization_controller_thorlabs_mpc320.py` to match the actual serial number of the device.

I am running Linux; @hhatpsi , will this code work on MacOS?

I have tried to mark some of the major unfinished work with `TODO`. There is probably still more that is missing or could be improved. The code also needs documentation.

My suggestion is that if @TomShen1234 can run the hardware tests against this branch, and there are no major problems found while @hhatpsi and @TomShen1234 review this PR, that we merge this PR and then continue work in additional, smaller PRs.

### CODE REVIEW

**Comment by auspicacious** [comment]
@master-of-ppap you should look at this code as well.

**Comment by TomShen1234** [comment]
I tried the codes and the hardware test. 
1. The tests (by extension, the code) don't quite work on macOS. The reason is that the serial device does not have an interface exposed in the `/dev` folder. I presume this is a drivers issue? But I had a quick peek around the internet and cannot find a suitable driver. 
2. I used a Linux virtual machine to test the code. Works fine for me. I'm wondering if it's not possible to get it working directly on macOS, is it possible to setup something like Docker? Using a VM requires a lot of work just to setup the dev environment every time some changes needs to be made.
3. It looks like we need to modify the serial number within the code. I'm thinking if it's better if we expose it as an option to be passed in the hardware test. I think `pytest` supports this.
4. Shall we do something about the `example.py` in the root directory? Seems like that's also a hardware test. If it's actually an example, maybe it's better to go in the readme?

**Comment by hhatpsi** [comment]
> * The tests (by extension, the code) don't quite work on macOS. The reason is that the serial device does not have an interface exposed in the `/dev` folder. I presume this is a drivers issue? But I had a quick peek around the internet and cannot find a suitable driver.

You can find the FTDI driver for macOS from [here](https://ftdichip.com/drivers/vcp-drivers/). You can also find the installation guide document [here](https://www.ftdichip.com/Support/Documents/InstallGuides/Mac_OS_X_Installation_Guide.pdf).  I've tried just one time to install one of the driver from the list for one other device, but It didn't work.  I think we need to apply additional configuration!

**Comment by auspicacious** [comment]
>     1. The tests (by extension, the code) don't quite work on macOS. The reason is that the serial device does not have an interface exposed in the `/dev` folder. I presume this is a drivers issue? But I had a quick peek around the internet and cannot find a suitable driver.

Yeah, I wonder about this. I [did a quick search](https://duckduckgo.com/?t=ffab&q=macos+usb+serial+device&ia=web) and indications are that there should be files that look something like `/dev/tty`. Another search result indicates that FTDI USB to serial chips (which we're using) work even on M1 Mac. I'll see if I can work this out with a Mac user tomorrow.

>     2. I used a Linux virtual machine to test the code. Works fine for me. I'm wondering if it's not possible to get it working directly on macOS, is it possible to setup something like Docker? Using a VM requires a lot of work just to setup the dev environment every time some changes needs to be made.

Yes, if you were able to forward your USB devices into a VM, most likely you can forward them into a Docker host VM, then into a Docker container inside this VM. We can set up VSCode integration like we have for other projects. It is theoretically a little tricky since we don't know the USB device filename we want to forward before we run the program.

FWIW we could also [directly integrate VSCode with a plain VM](https://code.visualstudio.com/docs/remote/ssh), AFAIK. ([emacs can do this too](https://www.gnu.org/software/emacs/manual/html_node/emacs/Remote-Files.html)). In general, I think this is a pretty good option for developers to have a flexible, Linux-based development environment, especially if the developer is using Windows.

This is all assuming we can't figure out why it's not working on MacOS.

Anyway, this is all for another PR.

By the way, another thing we don't support in the current PR is connecting by port name. You can only connect by serial number. We may need to support both in the future.

>     3. It looks like we need to modify the serial number within the code. I'm thinking if it's better if we expose it as an option to be passed in the hardware test. I think `pytest` supports this.

OK, but let's do that in another PR.

>     4. Shall we do something about the `example.py` in the root directory? Seems like that's also a hardware test. If it's actually an example, maybe it's better to go in the readme?

As we move existing Thorlabs devices into this new framework, we will write some test files for them. That's probably when we should delete `example.py`.

**Comment by TomShen1234** [comment]
> Another search result indicates that FTDI USB to serial chips (which we're using) work even on M1 Mac. I'll see if I can work this out with a Mac user tomorrow.

Interestingly enough, it shows up in the Mac's USB device manager, with the serial number also being present and correct. It's just that python's serial library can't find it (presumably because the device file didn't show up). I even did a diff of `/dev` before and after plugging it in, no difference.

> Yes, if you were able to forward your USB devices into a VM, most likely you can forward them into a Docker host VM, then into a Docker container inside this VM. We can set up VSCode integration like we have for other projects. It is theoretically a little tricky since we don't know the USB device filename we want to forward before we run the program.

For today, I installed the SSH plugin in VSCode and managed to get it working efficiently enough once it's setup. 

Since this is not really a Python's problem (probably due to Mac's driver), and we'll fix others in separate PRs, I'll approve this for now.

**Review by TomShen1234 — APPROVED** [review]

**Pull request merged**
