### PR TITLE
Add Sphinx documentation, automatically generate API docs

### PR DESCRIPTION
**Pull request by auspicacious**
Closes https://github.com/moonshot-nagayama-pj/PnPQ/issues/71

I'm still not 100% happy with the output formatting, but this is a start.

If you would like to see the output, check out this branch, run `bin/check.bash`, and then open the file `sphinx/build/html/index.html`.

### CODE REVIEW

**Comment by auspicacious** [comment]
That's odd, the check script worked locally. Looking into it now.

**Comment by auspicacious** [comment]
That's fixed. Sphinx was complaining about a missing directory.

**Review by TomShen1234 — COMMENTED** [review]
It works, but how should we host this site? 
Maybe host it in Github Page via a worker?
Apart from that (and the doc being slightly messy and hard to read), I think it's good.

**Comment by auspicacious** [comment]
@TomShen1234 See https://github.com/moonshot-nagayama-pj/PnPQ/issues/78 for publishing. I would like to keep this PR scoped to the initial generation process, especially since we don't have a lot of documentation to publish yet.

Could you approve this PR if there's no other comments?

**Review by TomShen1234 — APPROVED** [review]
Alright

**Comment by master-of-ppap** [comment]
This looks very nice. This will be very helpful for sure. Should we start updating the docstrings of some functions to hyperlinks like you said previously?

**Comment by auspicacious** [comment]
@master-of-ppap I did update the one, I'm not sure how many others exist: https://github.com/moonshot-nagayama-pj/PnPQ/pull/77/files#diff-b957e7273e2cb620ca5b5e58848356de109c0d8d8854553cf6caac5a28c951fbR141

In general, let's start thinking more about documentation, especially as we start to implement more driver classes.

**Comment by master-of-ppap** [comment]
@auspicacious Oh yes nice, but I think there are still some more around the code.
For example, on line 137 in protocol.py
```py
@enum.unique
class JogDirection(int, Enum):
    """Used in MSMSG_MOT_MOVE_JOG."""

    FORWARD = 0x01
    REVERSE = 0x02
```

and also the stopmode enum above also could be converted into links as well.
This is gonna be very useful I can tell.

**Pull request merged**
